image: haritz4998/gitlab-kubectl-gcloud-docker-plugin:v0.1

services:
  - docker:18.09.7-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

stages:
  - validate
  - build-deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

validate:
  image: node:14.4.0-alpine3.12
  stage: validate
  script:
    - npm install
  only:
    - prod
  cache:
    paths:
      - node_modules/

deploy-prod:
  stage: build-deploy
  variables:
    DOCKER_IMAGE_TAG: "${DOCKER_IMAGE_TAG}"
    DEPLOYMENT_NAME: "$GCR_NAME"
  script:
    - docker info
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - docker login -u _json_key --password-stdin https://us.gcr.io < key.json
    - docker pull ${DOCKER_IMAGE_TAG}:latest || true
    - docker build -f Dockerfile.bank --cache-from "${DOCKER_IMAGE_TAG}" -t "${DOCKER_IMAGE_TAG}:$CI_COMMIT_TAG" .
    - docker push ${DOCKER_IMAGE_TAG}

    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud run deploy ${DEPLOYMENT_NAME} --image ${DOCKER_IMAGE_TAG}:$CI_COMMIT_TAG --region=asia-southeast1 --platform managed
  only:
    - prod
  when: manual
  cache:
    paths:
      - node_modules/